sidebar_title: "LiuXiujun<br>Notebook"
sidebar_subtitle: "筆記"

truncate_len: 60

archives: true
rss: atom.xml

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] for livere.com
disqus: # [short_name] for disqus.com
